#!/bin/zsh

# Colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

# Disable compfix warning
ZSH_DISABLE_COMPFIX=true 

# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# NVM 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Custom $PATH with extra locations.
export PATH=$HOME/Library/Python/3.9/bin:/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:$HOME/bin:$HOME/go/bin:/usr/local/git/bin:$HOME/.composer/vendor/bin:$PATH

# ALIASES

# better cat with syntax highlighting
alias cat="bat"

# Open webstorm app
alias ws="open -a 'WebStorm.app'"
# Open VSCode Insiders
alias vsc="open -a 'Visual Studio Code - Insiders.app'"

# ts-node
alias ts="ts-node"

# Update ZSH
alias sz="source ~/.zshrc"

# Chezmoi
alias cze="chezmoi edit"
alias czu="chezmoi update"
alias cza="chezmoi apply"
alias czp="chezmoi git add . && chezmoi git -- commit -m 'update dotfiles' && chezmoi git push"

# Yabai 
alias yabr="brew services restart yabai"
alias yabs="brew services start yabai"
alias yabk="brew services stop yabai"

# Dotfiles, zsh
alias sz="source ~/.zshrc"
alias dfu="czu && yabr"

# Utils
killport() {
  if lsof -i tcp:"$*" >/dev/null 2>&1; then
    if lsof -i tcp:"$*" | awk 'NR!=1 {print $2}' | xargs kill -9 2>/dev/null; then
      echo -e "${GREEN}Successfully killed process running on port $*${RESET}"
    else
      echo -e "${RED}Error: Something went wrong while trying to kill the process on port $*${RESET}"
    fi
  else
    echo -e "${YELLOW}There is nothing running on port $*${RESET}"
  fi
}