#!/bin/zsh

# -----------------------------------------------------------------------------
# --- OH-MY-ZSH and Terminal ---
# -----------------------------------------------------------------------------

# Source oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

# Disable compfix warning
ZSH_DISABLE_COMPFIX=true

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
  git

  # TODO: Check these out
  # vscode
  # k 
  # vscode
  # zsh-autosuggestions
  # zsh-syntax-highlighting
)

# TERMINAL TITLE

# Set name of the application in the terminal tab
function set_name () {
  local rel_path="${PWD/$HOME/~}"
  echo -ne "\033]0;$rel_path\007"
}

# Update title on directory change
if [ -n "$ZSH_VERSION" ]; then
  precmd_functions+=(set_name)
elif [ -n "$BASH_VERSION" ]; then
  PROMPT_COMMAND='set_name'
fi



# -----------------------------------------------------------------------------
# --- Lazy load package managers ---
# -----------------------------------------------------------------------------

## Pyenv (lazy load)
pyenv() {
  unset -f pyenv
  export PYENV_ROOT="$HOME/.pyenv"
  [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(command pyenv init -)"
  pyenv "$@"
}

## Kubernetes (lazy load)
_kubectl_lazy_load() {
  unset -f kubectl _kubectl_lazy_load
  source <(kubectl completion zsh)
  kubectl "$@"
}
alias kubectl="_kubectl_lazy_load"



# -----------------------------------------------------------------------------
# --- PATH ALTERATIONS ---
# -----------------------------------------------------------------------------

# Homebrew
export PATH="$PATH:/opt/homebrew/bin"

# fnm
export PATH="$PATH:/home/$USER/.fnm"

# Local bin and sbin
export PATH="$PATH:/usr/local/bin:/usr/local/sbin"

# Personal bin
export PATH="$PATH:$HOME/bin"

# Go
export PATH="$PATH:$HOME/go/bin"

# Git
export PATH="$PATH:/usr/local/git/bin"

# Composer
export PATH="$PATH:$HOME/.composer/vendor/bin"

# Hana DB Client
export PATH="$PATH:/Applications/sap/hdbclient"

# Cargo
export PATH="$PATH:$HOME/.cargo/bin"

# Visual Studio Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Windsurf
export PATH="$PATH:/$HOME/.codeium/windsurf/bin"

# My custom scripts
export PATH="$PATH:$HOME/code/productivity/dotfiles/scripts/bin"

# Bun
export PATH="$PATH:$HOME/.bun/bin"

# Export PATH to apply all changes
export PATH

# PKG_CONFIG_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig



# -----------------------------------------------------------------------------
# --- ALIASES ---
# -----------------------------------------------------------------------------

## Git
alias gai="git llm"
alias gc="git commit -m"
alias ginit="git init && git add . && git commit -m 'init'"
alias gl="git l"
alias gs="git status"

## Open webstorm app
alias ws="open -a 'WebStorm.app'"

## Bun 
alias b="bun"

# Python
alias py="python3"
alias pip="pip3"

## Open VSCode
alias c="open -a 'Cursor.app'"

## ts-node
alias ts="ts-node"

## Dotfiles edit, update, apply and push
alias dote="c ~/.local/share/chezmoi"
alias dotu="chezmoi update"
alias dota="chezmoi apply"
alias dotp="chezmoi git add . && chezmoi git -- commit -m 'update dotfiles' && chezmoi git push"

## Yabai
alias yabr="brew services restart yabai"
alias yabs="brew services start yabai"
alias yabk="brew services stop yabai"

## Source Zsh
alias sz="source ~/.zshrc"

## Homelab
alias homelab-deploy="ssh maciek@lenovo 'cd ~/homelab && ./scripts/deploy.sh'"

## work
source $HOME/.zshrc.work



# -----------------------------------------------------------------------------
# --- UTILS ---
# -----------------------------------------------------------------------------

## Kill port
killport() {
  if lsof -i tcp:"$*" >/dev/null 2>&1; then
    if lsof -i tcp:"$*" | awk 'NR!=1 {print $2}' | xargs kill -9 2>/dev/null; then
      echo -e "${GREEN}Successfully killed process running on port $*${RESET}"
    else
      echo -e "${RED}Error: Something went wrong while trying to kill the process on port $*${RESET}"
    fi
  else
    echo -e "${YELLOW}There is nothing running on port $*${RESET}"
  fi
}



# -----------------------------------------------------------------------------
# --- OTHER ---
# -----------------------------------------------------------------------------

## Setup zoxide (better cd)
eval "$(zoxide init --cmd  cd zsh)"

## Setup fzf (fuzzy finder)
source <(fzf --zsh)

## Source Bun
[ -s "/Users/sitkom/.bun/_bun" ] && source "/Users/sitkom/.bun/_bun"

## Setup fnm
eval "$(fnm env --use-on-cd --version-file-strategy=recursive --corepack-enabled)"
