#!/bin/zsh

# Colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)

# Disable compfix warning
ZSH_DISABLE_COMPFIX=true

# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# TERMINAL TITLE

# Set name of the application in the terminal tab
function set_name () {
  local rel_path="${PWD/$HOME/~}"
  echo -ne "\033]0;$rel_path\007"
}

# Update title on directory change
if [ -n "$ZSH_VERSION" ]; then
  precmd_functions+=(set_name)
elif [ -n "$BASH_VERSION" ]; then
  PROMPT_COMMAND='set_name'
fi


# PATH ALTERATIONS
# Start with current PATH
PATH="$PATH:"

# Python
PATH="$PATH:$HOME/Library/Python/3.9/bin"

# Homebrew
PATH="$PATH:/opt/homebrew/bin"

# Local bin and sbin
PATH="$PATH:/usr/local/bin:/usr/local/sbin"

# Personal bin
PATH="$PATH:$HOME/bin"

# Go
PATH="$PATH:$HOME/go/bin"

# Git
PATH="$PATH:/usr/local/git/bin"

# Composer
PATH="$PATH:$HOME/.composer/vendor/bin"

# Visual Studio Code
PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# fnm
PATH="$PATH:/home/$USER/.fnm"
eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"

# Visual Studio Code Insiders
export PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"


# ALIASES

## Git
alias ginit="git init && git add . && git commit -m 'init'"
alias gc="git commit -m"

## Open webstorm app
alias ws="open -a 'WebStorm.app'"

## Open VSCode Insiders
alias c="open -a 'Visual Studio Code - Insiders.app'"

## ts-node
alias ts="ts-node"

## Update ZSH
alias sz="source ~/.zshrc"

## Dotfiles edit, update, apply and push
alias dote="c ~/.local/share/chezmoi"
alias dotu="chezmoi update"
alias dota="chezmoi apply"
alias dotp="chezmoi git add . && chezmoi git -- commit -m 'update dotfiles' && chezmoi git push"

## Yabai
alias yabr="brew services restart yabai"
alias yabs="brew services start yabai"
alias yabk="brew services stop yabai"

## zsh
alias sz="source ~/.zshrc"

## work
source $HOME/.zshrc.work


# UTILS

## Kill port
killport() {
  if lsof -i tcp:"$*" >/dev/null 2>&1; then
    if lsof -i tcp:"$*" | awk 'NR!=1 {print $2}' | xargs kill -9 2>/dev/null; then
      echo -e "${GREEN}Successfully killed process running on port $*${RESET}"
    else
      echo -e "${RED}Error: Something went wrong while trying to kill the process on port $*${RESET}"
    fi
  else
    echo -e "${YELLOW}There is nothing running on port $*${RESET}"
  fi
}

